# Generated by Django 3.2.12 on 2024-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapp',
            name='private_repo',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='githubapp',
            name='public_repo',
            field=models.TextField(default='None'),
        ),
    ]
